name: GitHub Activity Update

on:
  workflow_run:
    workflows: ["GitHub Profile Stats"]
    types:
      - completed
    branches: [main-2rd]
  schedule:
    # 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main-2rd
          fetch-depth: 0

      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update recent activity'
          MAX_LINES: 10
          TARGET_FILE: ./README.md
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com

      - name: Commit activity updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main-2rd --rebase
          git add README.md
          git commit -m 'Update GitHub activity' || true
          git push origin main-2rd || git pull --rebase origin main-2rd && git push origin main-2rd