name: GitHub Activity

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main-2rd

      - uses: cheesits456/github-activity-readme@16bd144b812ce901e0693fee5c36c02e75e6b4a7
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit activity updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main-2rd --rebase  # Add this line
          git add README.md
          git commit -m 'Update GitHub activity' || true
          git push origin main-2rd